monolog:
    channels:
        - deprecation
        - app_errors  # 👈 Add a custom channel for logging HTTP errors

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

            app_errors:  # 👈 NEW: Log HTTP 4xx/5xx errors to a custom file
                type: stream
                path: "%kernel.logs_dir%/http_errors_dev.log"
                level: error
                channels: [app_errors]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json

            app_errors:  # 👈 NEW: Log errors separately in production
                type: stream
                path: "%kernel.logs_dir%/http_errors_prod.log"
                level: error
                channels: [app_errors]

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
