controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix:
        en: '/en'
        sk: '/'

image_upload:
    path: /image/{size}/{imageName}
    controller: App\Controller\ImageController::uploaded
    methods: [GET]  # Assuming this is a GET request, adjust if it's POST or another method
    requirements:
        size: 'original|small|medium|big'
        imageName: '[^/]+'
    defaults:
        size: 'original'  # Default size if none is provided
