controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix:
        en: '/en'
        sk: '/'

image_controller:
    resource: ../src/Controller/ImageController.php
    type: attribute
